<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\AdajaController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\BerakhlakController;
use App\Http\Controllers\ExtensionController;
use App\Http\Controllers\FileManagerController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\MakroController;
use App\Http\Controllers\BakuController;
use App\Http\Controllers\BMNController;
use App\Http\Controllers\FormulirController;
use App\Http\Controllers\InstrumenController;
use App\Http\Controllers\MikrobiologiController;
use App\Http\Controllers\MikroController;
use App\Http\Controllers\MutuController;
use App\Http\Controllers\NotifyController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ReagensiaController;
use App\Http\Controllers\KuantitatifController;
use App\Http\Controllers\KualitatifController;
use App\Http\Controllers\RujukanController;
use App\Http\Controllers\SappaiController;
use App\Http\Controllers\SikamaController;
use App\Http\Controllers\SinonimController;
use App\Http\Controllers\OperasionalController;
use App\Http\Controllers\PtlController;
use App\Http\Controllers\RujukanNewController;
use App\Http\Controllers\SeppuloRujukanController;
use App\Http\Controllers\SerambiController;
use App\Http\Controllers\SipintarController;
use App\Http\Controllers\SiyappController;
use App\Http\Controllers\SmapController;
use App\Http\Controllers\SmileController;
use App\Http\Controllers\SPDController;
use App\Http\Controllers\SudokuController;
use App\Http\Controllers\SukuController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\UlpkController;
use App\Http\Controllers\UserController;
use App\Models\Extension;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');

Auth::routes(['verify' => true]);

Route :: middleware(['auth','verified','banned'])->group( function (){
Route::get('/home',[App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route :: get ('/userv',[UserController::class,'index'])->middleware('check-permission:superadmin');
Route :: get ('/useri',[UserController::class,'create'])->middleware('check-permission:superadmin');
Route :: post ('/useri',[UserController::class,'store'])->middleware('check-permission:superadmin');
Route ::delete('users/{id}', [UserController::class, 'destroy'])->name('users.delete')->middleware('check-permission:superadmin');
Route :: get ('/user/{id}/edit',[UserController::class,'edit'])->middleware('check-permission:superadmin');
Route :: put('usere/{id}',[UserController::class,'update'])->middleware('check-permission:superadmin');

Route :: get ('/userl',[ProfileController::class,'index']);
Route :: get ('/user/{id}/profile',[ProfileController::class,'show']);
Route :: get ('/user/{id}',[ProfileController::class,'showim']);
Route :: get ('/user/{id}/editprof',[ProfileController::class,'edit']);
Route :: put ('/user/{id}/editpass',[ProfileController::class,'updatepass']);
Route :: put ('/user/{id}/editprof',[ProfileController::class,'updateprof']);
Route :: put ('/user/{id}/editpeg',[ProfileController::class,'updatepeg']);
Route :: put ('/user/{id}/editsosmed',[ProfileController::class,'updatesosmed']);
Route :: put ('/user/{id}/editaddr',[ProfileController::class,'updateaddr']);

Route::get('/categories', [CategoryController::class,'index'])->middleware('check-permission:superadmin');
Route::get('/catinput',[CategoryController::class,'create'])->middleware('check-permission:superadmin');
Route::post('/catstore',[CategoryController::class,'store'])->middleware('check-permission:superadmin');
Route ::delete('/category/{id}', [CategoryController::class, 'destroy'])->name('category.delete')->middleware('check-permission:superadmin');
Route :: get ('/category/{id}/edit',[CategoryController::class,'edit'])->middleware('check-permission:superadmin');
Route :: put('/category/{id}',[CategoryController::class,'update'])->middleware('check-permission:superadmin');

Route :: get('/tags', [TagController::class,'index'])->middleware('check-permission:superadmin');
Route::get('/taginput',[TagController::class,'create'])->middleware('check-permission:superadmin');
Route::post('/tagstore',[TagController::class,'store'])->middleware('check-permission:superadmin');
Route ::delete('/tag/{id}', [TagController::class, 'destroy'])->name('tag.delete')->middleware('check-permission:superadmin');
Route :: get ('/tag/{id}/edit',[TagController::class,'edit'])->middleware('check-permission:superadmin');
Route :: put('/tag/{id}',[TagController::class,'update'])->middleware('check-permission:superadmin');

// Manage Posts
Route::get('posts/trash', [App\Http\Controllers\PostController::class , 'trash'])->name('posts.trash')->middleware('check-permission:superadmin');
Route::post('posts/trash/{id}/restore', [App\Http\Controllers\PostController::class , 'restore'])->name('posts.restore')->middleware('check-permission:superadmin');
Route::delete('posts/{id}/delete-permanent', [App\Http\Controllers\PostController::class,'deletePermanent'])->name('posts.deletePermanent')->middleware('check-permission:superadmin');
Route::resource('posts', App\Http\Controllers\PostController::class)->middleware('check-permission:superadmin');

Route::post('ckeditor/upload', [PostController::class,'upload'])->name('ckeditor.image-upload')->middleware('check-permission:superadmin');
Route::get('filemanager', [FileManagerController::class, 'index'])->middleware('check-permission:superadmin');
Route::get('preview', [FileManagerController::class, 'preview'])->name('fm.preview')->middleware('check-permission:superadmin');

Route :: get ('/latar',[ExtensionController::class,'latar'])->middleware('check-permission:superadmin');;
Route :: put ('/ulatar/{id}',[ExtensionController::class,'update'])->middleware('check-permission:superadmin');;
Route :: get ('/vm',[ExtensionController::class,'vm'])->middleware('check-permission:superadmin');;
Route :: put ('/uvm/{id}',[ExtensionController::class,'update'])->middleware('check-permission:superadmin');;
Route :: get ('/tf',[ExtensionController::class,'tf'])->middleware('check-permission:superadmin');;
Route :: put ('/utf/{id}',[ExtensionController::class,'update'])->middleware('check-permission:superadmin');;
Route :: get ('/so',[ExtensionController::class,'so'])->middleware('check-permission:superadmin');;
Route :: put ('/uso/{id}',[ExtensionController::class,'update'])->middleware('check-permission:superadmin');;

Route :: get('/notify',[NotifyController::class,'index']);
Route :: get('/notif_detail/{id}',[NotifyController::class,'show']);

Route :: get('/siyapp',[SiyappController::class,'index']);
Route :: get('/formulir',[SiyappController::class,'formulir']);
Route :: get('/laporan',[SiyappController::class,'laporan'])->name('siyapp.view-non-it');
Route :: get('/laporan-it',[SiyappController::class,'it'])->name('siyapp.view-it');
Route :: post('/siyappstore',[SiyappController::class,'store']);
Route :: get('/laporan/{id}/edit',[SiyappController::class,'edit'])->middleware('check-permission:perlengkapan|superadmin|it');
Route :: put('/laporan/{id}',[SiyappController::class,'update'])->middleware('check-permission:perlengkapan|superadmin|it');
Route :: delete('/siyapp/{id}/delete',[SiyappController::class,'destroy'])->middleware('check-permission:superadmin');
Route :: get('/form-cetak',[SiyappController::class,'cetak'])->middleware('check-permission:perlengkapan|superadmin|it');
Route :: get ('/showw/{id}',[SiyappController::class,'show'])->middleware('check-permission:perlengkapan|superadmin|it');
Route :: post('/siyappcetak',[SiyappController::class,'scetak'])->middleware('check-permission:perlengkapan|superadmin|it');
Route :: get('/detail-laporan-siyapp/{id}',[SiyappController::class,'detail']);
Route :: post('/konfirmasi-siyapp/{id}',[SiyappController::class,'konfir'])->middleware('check-permission:perlengkapan|superadmin|it');
Route :: get ('/show-kode-barang/{id}',[SiyappController::class,'showBarang']);

Route :: get('/smap-pedoman',[SmapController::class,'pedomanLvlA']);
Route :: get('/smap-pedoman/input-pedoman/',[SmapController::class,'pedomanLvlAInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/smap-pedoman/pedoman-store',[SmapController::class,'pedomanLvlAStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/smap-pedoman/{id}/detail-revisi/',[SmapController::class,'pedomanLvlB']);
Route :: post('/smap-pedoman/{id}/view-file',[SmapController::class,'view_file']);
Route :: get('/smap-pedoman/{id}/edit',[SmapController::class,'pedomanLvlAEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/smap-pedoman/{id}/update',[SmapController::class,'pedomanLvlAUpdate'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/smap-pedoman/{id}/delete',[SmapController::class,'pedomanLvlADestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/smap-pedoman/revisi/{id}/input-revisi',[SmapController::class,'pedomanLvlBInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/smap-pedoman/{id}/input-revisi',[SmapController::class,'pedomanLvlBStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/smap-pedoman/{id}/edit-revisi',[SmapController::class,'pedomanLvlBEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/smap-pedoman/{id}/update-revisi',[SmapController::class,'pedomanLvlBUpdate'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/smap-pedoman/{id}/delete-revisi',[SmapController::class,'pedomanLvlBDestroy'])->middleware('check-permission:superadmin|laboratorium');

Route :: get('/smap-sop',[SmapController::class,'sopLvlA']);
Route :: get('/smap-sop/input-sop/',[SmapController::class,'sopLvlAInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/smap-sop/sop-store',[SmapController::class,'sopLvlAStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/smap-sop/{id}/detail-revisi/',[SmapController::class,'sopLvlB']);
Route :: post('/smap-sop/{id}/view-file',[SmapController::class,'view_file']);
Route :: get('/smap-sop/{id}/edit',[SmapController::class,'sopLvlAEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/smap-sop/{id}/update',[SmapController::class,'sopLvlAUpdate'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/smap-sop/{id}/delete',[SmapController::class,'sopLvlADestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/smap-sop/revisi/{id}/input-revisi',[SmapController::class,'sopLvlBInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/smap-sop/{id}/input-revisi',[SmapController::class,'sopLvlBStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/smap-sop/{id}/edit-revisi',[SmapController::class,'sopLvlBEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/smap-sop/{id}/update-revisi',[SmapController::class,'sopLvlBUpdate'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/smap-sop/{id}/delete-revisi',[SmapController::class,'sopLvlBDestroy'])->middleware('check-permission:superadmin|laboratorium');

Route :: get('/smap-ik',[SmapController::class,'ikLvlA']);
Route :: get('/smap-ik/input-ik/',[SmapController::class,'ikLvlAInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/smap-ik/ik-store',[SmapController::class,'ikLvlAStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/smap-ik/{id}/detail-revisi/',[SmapController::class,'ikLvlB']);
Route :: post('/smap-ik/{id}/view-file',[SmapController::class,'view_file']);
Route :: get('/smap-ik/{id}/edit',[SmapController::class,'ikLvlAEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/smap-ik/{id}/update',[SmapController::class,'ikLvlAUpdate'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/smap-ik/{id}/delete',[SmapController::class,'ikLvlADestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/smap-ik/revisi/{id}/input-revisi',[SmapController::class,'ikLvlBInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/smap-ik/{id}/input-revisi',[SmapController::class,'ikLvlBStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/smap-ik/{id}/edit-revisi',[SmapController::class,'ikLvlBEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/smap-ik/{id}/update-revisi',[SmapController::class,'ikLvlBUpdate'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/smap-ik/{id}/delete-revisi',[SmapController::class,'ikLvlBDestroy'])->middleware('check-permission:superadmin|laboratorium');

Route :: get('/smap-form',[SmapController::class,'formLvlA']);
Route :: get('/smap-form/input-form/',[SmapController::class,'formLvlAInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/smap-form/form-store',[SmapController::class,'formLvlAStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/smap-form/{id}/detail-revisi/',[SmapController::class,'formLvlB']);
Route :: post('/smap-form/{id}/view-file',[SmapController::class,'view_file']);
Route :: get('/smap-form/{id}/edit',[SmapController::class,'formLvlAEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/smap-form/{id}/update',[SmapController::class,'formLvlAUpdate'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/smap-form/{id}/delete',[SmapController::class,'formLvlADestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/smap-form/revisi/{id}/input-revisi',[SmapController::class,'formLvlBInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/smap-form/{id}/input-revisi',[SmapController::class,'formLvlBStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/smap-form/{id}/edit-revisi',[SmapController::class,'formLvlBEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/smap-form/{id}/update-revisi',[SmapController::class,'formLvlBUpdate'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/smap-form/{id}/delete-revisi',[SmapController::class,'formLvlBDestroy'])->middleware('check-permission:superadmin|laboratorium');

Route :: get('/sappaiadmin',[SappaiController::class,'index']);
Route :: get('/user_sappai',[SappaiController::class,'user'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: get('/useri_sappai',[SappaiController::class,'useri'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: post('/user_store',[SappaiController::class,'store'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: delete('/user_sappai/delete/{id}',[SappaiController::class,'destroy'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: post('/user_cetak',[SappaiController::class,'cetak_user'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: get('/sample_sappai',[SappaiController::class,'sample'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: get('/samplei_sappai',[SappaiController::class,'samplei'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: post('/sample_store',[SappaiController::class,'sample_store'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: get('/sample_sappai/{id}/edit',[SappaiController::class,'sample_edit'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: put('/sample_update/{id}',[SappaiController::class,'sample_update'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: get('/sample_detail/{id}',[SappaiController::class,'sample_detail'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: delete('/sample_sappai/delete/{id}',[SappaiController::class,'sample_destroy'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: get('/kuisioner',[SappaiController::class,'kuisioner'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: get('/kuis_download',[SappaiController::class,'cetak'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');
Route :: delete('/kuisioner/delete/{id}',[SappaiController::class,'kuisioner_destroy'])->middleware('check-permission:perlengkapan|laboratorium|superadmin');

Route :: get('/sudoku',[SudokuController::class,'index']);
Route :: get('/manual_org',[SudokuController::class,'man_orgv']);
Route :: get('/manual_org_input',[SudokuController::class,'man_orgi'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/man_org_store',[SudokuController::class,'man_org_store'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/file_man_org/{id}',[SudokuController::class,'view_file']);
Route :: get('/man_org/{id}/detail',[SudokuController::class,'manOrgDetailV']);
Route :: get('/detail-judul-input/{id}',[SudokuController::class,'detailJudul']);
Route :: post('/man-org-judul-store/{id}',[SudokuController::class,'manOrgJudulStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/revisi-lvl-a/{lvla}/{id}/{cat}',[SudokuController::class,'revisiDetail']);
Route :: get('/detail-revisi-input/{lvla}/{id}/{cat}',[SudokuController::class,'revisiInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/revisi-store/{lvla}/{id}/{cat}',[SudokuController::class,'revisiStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/man_org_judul/{id}/delete',[SudokuController::class,'destroyJudul'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('man_org/{id}/delete',[SudokuController::class,'destroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/sudoku-storage',[SudokuController::class,'storage']);
Route :: post('/storage-store',[SudokuController::class,'storageStore']);
Route :: get('/sudoku-storage-download/storage/sudoku-storage/{id}',[SudokuController::class,'download']);
Route :: get('/sudoku-storage-add',[SudokuController::class,'storageAdd']);
Route :: delete('/sudoku-storage/{id}/delete',[SudokuController::class,'delete']);
Route :: get('/sudoku-did-internal-bpom',[SudokuController::class,'didIntern']);
Route :: get('/sudoku-did-internal-bpom-mks',[SudokuController::class,'didInternBpom']);
Route :: get('/sudoku-did-internal-bpom-17025',[SudokuController::class,'didInternBpom17025']);

Route :: get('/ptl',[PtlController::class,'ptlLvlA']);
Route :: get('/ptl-input',[PtlController::class,'ptlLvlAInput']);
Route :: post('/ptl-store',[PtlController::class,'ptlLvlAStore']);
Route :: get('/ptl-revisi/{id}',[PtlController::class,'ptlLvlB']);
Route :: get('/ptl-revisi-input/{id}',[PtlController::class,'ptlLvlBInput']);
Route :: post('/ptl-revisi-store/{id}',[PtlController::class,'ptlLvlBStore']);
Route :: delete('/ptl/{id}/delete',[PtlController::class,'lvlADestroy']);
Route :: delete('/ptl-revisi/{id}/delete',[PtlController::class,'lvlBDestroy']);
Route :: post('/ptl-view/{id}',[PtlController::class,'view_file']);
Route :: get('/edit-ptl-revisi/{id}',[PtlController::class,'editRevisi'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/ptl-revisi-update/{id}',[PtlController::class,'updateRevisi'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/edit-ptl/{id}',[PtlController::class,'ptlLvlBEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/update-ptl/{id}',[PtlController::class,'ptlLvlBUpdate'])->middleware('check-permission:superadmin|laboratorium');

Route :: get('/makro',[MakroController::class,'makroLvlA']);
Route :: get('/proses-bisnis-input',[MakroController::class,'makroLvlAInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/proses-bisnis-store',[MakroController::class,'makroLvlAStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/proses-bisnis/{id}/delete',[MakroController::class,'makroLvlADestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/sub-proses-bisnis/{id}',[MakroController::class,'makroLvlB']);
Route :: get('/sub-proses-bisnis-input/{id}',[MakroController::class,'makroLvlBInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/proses-bisnis-store/{id}',[MakroController::class,'makroLvlBStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/sub-proses-bisnis/{id}/delete',[MakroController::class,'makroLvlBDestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/lintas-fungsi/{id}',[MakroController::class,'makroLvlC']);
Route :: get('/peta-lintas-fungsi-input/{id}',[MakroController::class,'makroLvlCInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/lintas-fungsi-store/{id}',[MakroController::class,'makroLvlCStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/lintas-fungsi/{id}/delete',[MakroController::class,'makroLvlCDestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/sop-makro/{id}',[MakroController::class,'makroLvlD']);
Route :: get('/sop-makro-input/{id}',[MakroController::class,'makroLvlDInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/sop-makro-store/{id}',[MakroController::class,'makroLvlDStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/sop-makro-view/{id}',[MakroController::class,'view_file']);
Route :: delete('/sop-makro/{id}/delete',[MakroController::class,'makroLvlDDestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/sop-makro/{id}/detail',[MakroController::class,'makroLvlE']);
Route :: get('/revisi-input/{id}',[MakroController::class,'makroLvlEInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/revisi-store/{id}',[MakroController::class,'makroLvlEStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/edit-makro-revisi/{id}',[MakroController::class,'editRevisi'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/makro-revisi-update/{id}',[MakroController::class,'updateRevisi'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/edit-peta-proses-bisnis/{id}',[MakroController::class,'makroLvlAEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/update-peta-proses-bisnis/{id}',[MakroController::class,'makroLvlAUpdate'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/edit-sub-proses-bisnis/{id}',[MakroController::class,'makroLvlBEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/update-sub-proses-bisnis/{id}',[MakroController::class,'makroLvlBUpdate'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/edit-lintas-fungsi/{id}',[MakroController::class,'makroLvlCEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/update-lintas-fungsi/{id}',[MakroController::class,'makroLvlCUpdate'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/edit-sop-makro/{id}',[MakroController::class,'makroLvlDEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/update-sop-makro/{id}',[MakroController::class,'makroLvlDUpdate'])->middleware('check-permission:superadmin|laboratorium');

Route :: get('/mikro',[MikroController::class,'mikroLvlA']);
Route :: get('/mikro-induk-input',[MikroController::class,'mikroLvlAInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/sop-makro-induk-store',[MikroController::class,'mikroLvlAStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/detail-mikro/{kode1}/{kode2}/{kode3}',[MikroController::class,'mikroLvlB']);
Route :: get('/detail-mikro-input/{kode1}/{kode2}/{kode3}',[MikroController::class,'mikroLvlBInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/sop-mikro-store',[MikroController::class,'mikroLvlBStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/detail-revisi/{id}',[MikroController::class,'mikroLvlC']);
Route :: get('/mikro-revisi-input/{id}',[MikroController::class,'mikroLvlCInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/mikro-revisi-store/{id}',[MikroController::class,'mikroLvlCStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/sop-mikro-view/{id}',[MikroController::class,'view_file']);
Route :: delete('/makro-induk/{id}/delete',[MikroController::class,'lvlADestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/mikro/{id}/delete',[MikroController::class,'lvlBDestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/mikro-revisi/{id}/delete',[MikroController::class,'lvlCDestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/edit-mikro-revisi/{id}',[MikroController::class,'editRevisi'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/mikro-revisi-update/{id}',[MikroController::class,'updateRevisi'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/edit-sop-mikro/{id}',[MikroController::class,'mikroLvlBEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/update-sop-mikro/{id}',[MikroController::class,'mikroLvlBUpdate'])->middleware('check-permission:superadmin|laboratorium');

Route :: get('/mutu-laboratorium',[MutuController::class,'mutuLvlA']);
Route :: get('/mutu-laboratorium-input',[MutuController::class,'mutuLvlAInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/mutu-laboratorium-store',[MutuController::class,'mutuLvlAStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/mutu-laboratorium-view/{id}',[MutuController::class,'view_file']);
Route :: delete('/mutu-laboratorium/{id}/delete',[MutuController::class,'lvlADestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/detail-revisi-mutu/{id}',[MutuController::class,'mutuLvlB']);
Route :: get('/revisi-mutu-input/{id}',[MutuController::class,'mutuLvlBInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/mutu-revisi/{id}/delete',[MutuController::class,'lvlBDestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/revisi-mutu-store/{id}',[MutuController::class,'mutuLvlBStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/edit-mutu-revisi/{id}',[MutuController::class,'editRevisi'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/mutu-revisi-update/{id}',[MutuController::class,'updateRevisi'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/edit-pjml/{id}',[MutuController::class,'pjmlLvlAEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/update-pjml/{id}',[MutuController::class,'pjmlLvlAUpdate'])->middleware('check-permission:superadmin|laboratorium');

Route :: get('/instruksi-kerja',[InstrumenController::class,'istrumenLvlA']);
Route :: get('/instruksi-kerja-input',[InstrumenController::class,'istrumenLvlAInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/mutu-lab-induk-store',[InstrumenController::class,'istrumenLvlAStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/detail-instruksi-kerja/{id}',[InstrumenController::class,'istrumenLvlB']);
Route :: get('/detail-instruksi-kerja-input/{id}',[InstrumenController::class,'istrumenLvlBInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/instruksi-kerja-store',[InstrumenController::class,'instrumenLvlBStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/instrumen-revisi/{id}',[InstrumenController::class,'instrumenLvlC']);
Route :: get('/instruksi-revisi-input/{id}',[InstrumenController::class,'instrumenLvlCInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/instruksi-revisi-store/{id}',[InstrumenController::class,'instrumenLvlCStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/mutu-induk/{id}/delete',[InstrumenController::class,'lvlADestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/instruksi-kerja/{id}/delete',[InstrumenController::class,'lvlBDestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/instruksi-revisi/{id}/delete',[InstrumenController::class,'lvlCDestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/instruksi-kerja-view/{id}',[InstrumenController::class,'view_file']);
Route :: get('/edit-instruksi-revisi/{id}',[InstrumenController::class,'editRevisi'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/instruksi-revisi-update/{id}',[InstrumenController::class,'updateRevisi'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/edit-instruksi-kerja/{id}',[InstrumenController::class,'instruksiLvlBEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/update-instruksi-kerja/{id}',[InstrumenController::class,'instruksiLvlBUpdate'])->middleware('check-permission:superadmin|laboratorium');

Route :: get('/dokumen-pendukung',[FormulirController::class,'formulirLvlA']);
Route :: get('/dokumen-pendukung-input',[FormulirController::class,'formulirLvlAInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/dokumen-pendukung-store',[FormulirController::class,'formulirLvlAStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/detail-formulir/{id}',[FormulirController::class,'formulirLvlB']);
Route :: get('/detail-formulir-input/{id}',[FormulirController::class,'formulirLvlBInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/detail-formulir-store',[FormulirController::class,'formulirLvlBStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/formulir-revisi/{id}',[FormulirController::class,'formulirLvlC']);
Route :: get('/formulir-revisi-input/{id}',[FormulirController::class,'formulirLvlCInput'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/formulir-revisi-store/{id}',[FormulirController::class,'formulirLvlCStore'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/formulir-induk/{id}/delete',[FormulirController::class,'lvlADestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/formulir/{id}/delete',[FormulirController::class,'lvlBDestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: delete('/formulir-revisi/{id}/delete',[FormulirController::class,'lvlCDestroy'])->middleware('check-permission:superadmin|laboratorium');
Route :: post('/formulir-view/{id}',[FormulirController::class,'view_file']);
Route :: get('/edit-formulir-revisi/{id}',[FormulirController::class,'editRevisi'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/formulir-revisi-update/{id}',[FormulirController::class,'updateRevisi'])->middleware('check-permission:superadmin|laboratorium');
Route :: get('/edit-formulir/{id}',[FormulirController::class,'formulirLvlBEdit'])->middleware('check-permission:superadmin|laboratorium');
Route :: put('/update-formulir/{id}',[FormulirController::class,'formulirLvlBUpdate'])->middleware('check-permission:superadmin|laboratorium');

Route :: get('/sinonim',[SinonimController::class,'index']);
Route :: get('/inventory',[SinonimController::class,'inventory']);
Route :: post('/inventorys',[SinonimController::class,'inventorystore']);
Route :: get('/inventoryv',[SinonimController::class,'inventoryview']);
Route :: delete('/inventoryd/{id}',[SinonimController::class,'inventorydelete']);

Route :: get('/reagensia',[ReagensiaController::class,'reagensia'])->middleware('check-permission:perlengkapan|superadmin');
Route :: post('/reagensias',[ReagensiaController::class,'reagensias'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get('/reagensiav',[ReagensiaController::class,'reagensiav']);
Route :: get('/reagensia/{id}/edit',[ReagensiaController::class,'reagensiae'])->middleware('check-permission:perlengkapan|superadmin');
Route :: put('/reagensia/{id}',[ReagensiaController::class,'reagensiau'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get ('/reagensiatrans/{id}',[ReagensiaController::class,'reagensiatransi'])->middleware('check-permission:perlengkapan|superadmin');
Route :: post('/reagensiatrans',[ReagensiaController::class,'reagensiatrans'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get('/reagensia/{id}/detail',[ReagensiaController::class,'reagensiatransv'])->middleware('check-permission:perlengkapan|superadmin');
Route :: delete('/reagensiad/{id}',[ReagensiaController::class,'reagensiad'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get('/rekap_reagen',[ReagensiaController::class,'rekap'])->middleware('check-permission:superadmin');
Route :: get('/reagen_formc',[ReagensiaController::class,'formc'])->middleware('check-permission:perlengkapan|superadmin');
Route :: post('/reagencetak',[ReagensiaController::class,'reagencetak'])->middleware('check-permission:perlengkapan|superadmin');

Route :: get('/mikrobiologiv',[MikrobiologiController::class,'mikrobiologiv']);
Route :: get('/mikrobiologi',[MikrobiologiController::class,'mikrobiologi'])->middleware('check-permission:perlengkapan|superadmin');
Route :: post('/mikrobiologis',[MikrobiologiController::class,'mikrobiologis'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get('/mikrobiologi/{id}/detail',[MikrobiologiController::class,'mikrobiologitransv'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get ('/mikrotrans/{id}',[MikrobiologiController::class,'mikrotransi'])->middleware('check-permission:perlengkapan|superadmin');
Route :: post('/mikrotrans',[MikrobiologiController::class,'mikrotrans'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get('/mikrobiologi/{id}/edit',[MikrobiologiController::class,'mikrobiologie'])->middleware('check-permission:perlengkapan|superadmin');
Route :: put('/mikrobiologi/{id}',[MikrobiologiController::class,'mikrobiologiu'])->middleware('check-permission:perlengkapan|superadmin');
Route :: delete('/mikrobiologid/{id}',[MikrobiologiController::class,'mikrobiologid'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get('/rekap_mikro',[MikrobiologiController::class,'rekap'])->middleware('check-permission:superadmin');
Route :: get('/mikro_formc',[MikrobiologiController::class,'formc'])->middleware('check-permission:perlengkapan|superadmin');
Route :: post('/mikrocetak',[MikrobiologiController::class,'mikrocetak'])->middleware('check-permission:perlengkapan|superadmin');

Route :: get('/operasionalv',[OperasionalController::class,'operasionalv']);
Route :: get('/operasional',[OperasionalController::class,'operasional'])->middleware('check-permission:perlengkapan|superadmin');
Route :: post('/operasionals',[OperasionalController::class,'operasionals'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get('/operasional/{id}/detail',[OperasionalController::class,'operasionaltransv'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get ('/operatrans/{id}',[OperasionalController::class,'operatransi'])->middleware('check-permission:perlengkapan|superadmin');
Route :: post('/operatrans',[OperasionalController::class,'operatrans'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get('/operasional/{id}/edit',[OperasionalController::class,'operasionale'])->middleware('check-permission:perlengkapan|superadmin');
Route :: put('/operasional/{id}',[OperasionalController::class,'operasionalu'])->middleware('check-permission:perlengkapan|superadmin');
Route :: delete('/operasionald/{id}',[OperasionalController::class,'operasionald'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get('/rekap_opera',[OperasionalController::class,'rekap'])->middleware('check-permission:superadmin');
Route :: get('/opera_formc',[OperasionalController::class,'formc'])->middleware('check-permission:perlengkapan|superadmin');
Route :: post('/operacetak',[OperasionalController::class,'operacetak'])->middleware('check-permission:perlengkapan|superadmin');

Route :: get('/kuantitatifv',[KuantitatifController::class,'kuantitatifv']);
Route :: get('/kuantitatif',[KuantitatifController::class,'kuantitatif'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: post('/kuantitatifs',[KuantitatifController::class,'kuantitatifs'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: get('/kuantitatif/{id}/detail',[KuantitatifController::class,'kuantitatiftransv'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: get ('/kuantitatiftrans/{id}',[KuantitatifController::class,'kuantransi'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: post('/kuantrans',[KuantitatifController::class,'kuantrans'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: get('/kuantitatif/{id}/edit',[KuantitatifController::class,'kuantitatife'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: put('/kuantitatif/{id}',[KuantitatifController::class,'kuantitatifu'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: delete('/kuantitatifd/{id}',[KuantitatifController::class,'kuantitatifd'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: get('/rekap_kuan',[KuantitatifController::class,'rekap'])->middleware('check-permission:superadmin');
Route :: get('/kuan_formc',[KuantitatifController::class,'formc'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: post('/kuancetak',[KuantitatifController::class,'kuancetak'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');

Route :: get('/kualitatifv',[KualitatifController::class,'kualitatifv']);
Route :: get('/kualitatif',[KualitatifController::class,'kualitatif'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: post('/kualitatifs',[KualitatifController::class,'kualitatifs'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: get('/kualitatif/{id}/detail',[KualitatifController::class,'kualitatiftransv'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: get ('/kualitatiftrans/{id}',[KualitatifController::class,'kualtransi'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: post('/kualtrans',[KualitatifController::class,'kualtrans'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: get('/kualitatif/{id}/edit',[KualitatifController::class,'kualitatife'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: put('/kualitatif/{id}',[KualitatifController::class,'kualitatifu'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: delete('/kualitatifd/{id}',[KualitatifController::class,'kualitatifd'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: get('/rekap_kual',[KualitatifController::class,'rekap'])->middleware('check-permission:superadmin');
Route :: get('/kual_formc',[KualitatifController::class,'formc'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: post('/kualcetak',[KualitatifController::class,'kualcetak'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');

Route :: get('/bakuv',[BakuController::class,'bakuv']);
Route :: get('/baku',[BakuController::class,'baku'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: post('/bakus',[BakuController::class,'bakus'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: get('/baku/{id}/detail',[BakuController::class,'bakutransv'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: get ('/bakutrans/{id}',[BakuController::class,'bakutransi'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: post('/bakutrans',[BakuController::class,'bakutrans'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: get('/baku/{id}/edit',[BakuController::class,'bakue'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: put('/baku/{id}',[BakuController::class,'bakuu'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: delete('/bakud/{id}',[BakuController::class,'bakud'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: get('/rekap_baku',[BakuController::class,'rekap'])->middleware('check-permission:superadmin');
Route :: get('/baku_formc',[BakuController::class,'formc'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: post('/bakucetak',[BakuController::class,'bakucetak'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');

Route :: get('/sukuv',[SukuController::class,'sukuv']);
Route :: get('/suku',[SukuController::class,'suku'])->middleware('check-permission:perlengkapan|superadmin');
Route :: post('/sukus',[SukuController::class,'sukus'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get('/suku/{id}/detail',[SukuController::class,'sukutransv'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get ('/sukutrans/{id}',[SukuController::class,'sukutransi'])->middleware('check-permission:perlengkapan|superadmin');
Route :: post('/sukutrans',[SukuController::class,'sukutrans'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get('/suku/{id}/edit',[SukuController::class,'sukue'])->middleware('check-permission:perlengkapan|superadmin');
Route :: put('/suku/{id}',[SukuController::class,'sukuu'])->middleware('check-permission:perlengkapan|superadmin');
Route :: delete('/sukud/{id}',[SukuController::class,'sukud'])->middleware('check-permission:perlengkapan|superadmin');
Route :: get('/rekap_suku',[SukuController::class,'rekap'])->middleware('check-permission:superadmin');
Route :: get('/suku_formc',[SukuController::class,'formc'])->middleware('check-permission:perlengkapan|superadmin|laboratorium');
Route :: post('/sukucetak',[SukuController::class,'sukucetak'])->middleware('check-permission:perlengkapan|superadmin');

Route :: get('/ulpk',[UlpkController::class,'index']);
Route :: get('/formulpk',[UlpkController::class,'formulir'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: post('/store',[UlpkController::class,'store'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: post('/updateulpk',[UlpkController::class,'updateulpk'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: get('/laporanulpk',[UlpkController::class,'laporanulpk'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: get('/ulpk/V.1/{id}/detail',[UlpkController::class,'ulpkdetail'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: get('/konsumen/{id}/edit',[UlpkController::class,'edit'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: put('/updateulpk/{id}',[UlpkController::class,'update'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: put('/updateulpkk/{id}',[UlpkController::class,'updatee'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: get('/cetakulpk',[UlpkController::class,'cetak'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: post('/formcetak',[UlpkController::class,'formcetak'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: get('/ulpkk',[UlpkController::class,'ulpk']);
Route :: delete('/ulpk/{id}/delete',[UlpkController::class,'delete'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: get('/ulpk/formulir-ulpk',[UlpkController::class,'formulir'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: post('/ulpk/store',[UlpkController::class,'ulpkStore'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: get('/ulpk/laporan-ulpk',[UlpkController::class,'laporanUlpkv2'])->name('ulpk.lapv2')->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: post('/ulpk/V.1/filter',[UlpkController::class,'filterV1'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: post('/ulpk/V.2/filter',[UlpkController::class,'filterV2'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: get('/ulpk/V.2/{id}/detail',[UlpkController::class,'ulpkDetailV2'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: get('/ulpk/{id}/edit',[UlpkController::class,'editUlpk'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: put('/ulpk/update/{id}',[UlpkController::class,'ulpkUpdate'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: get('/ulpk/download-ulpk',[UlpkController::class,'download'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: post('/ulpk/download-proses',[UlpkController::class,'downProses'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');
Route :: get('/sipintar/data-tamu/{id}/ulpk',[UlpkController::class,'sipintar'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi|pemeriksaan|pengujian|picpengujian|picpenindakan');

Route :: get('/rujukan',[RujukanController::class,'rujukan']);
Route :: get('/formrujukan',[RujukanController::class,'formrujuk'])->middleware('check-permission:infokom|superadmin|picinfokom');
Route :: post('/rujukans',[RujukanController::class,'store'])->middleware('check-permission:infokom|superadmin|picinfokom');
Route :: get('/rujukanv',[RujukanController::class,'index'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpengujian|picpenindakan');
Route :: get('/rujukan/{id}/detail',[RujukanController::class,'show'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpengujian|picpenindakan');
Route :: get('/rujukan/{id}/cetak',[RujukanController::class,'cetak'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpengujian|picpenindakan');
Route :: get('/rujukan/{id}/edit',[RujukanController::class,'edit'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpengujian|picpenindakan');
Route :: put('/rujukan/{id}/update',[RujukanController::class,'update'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpengujian|picpenindakan');
Route :: get('/rujukan/{id}/hasil',[RujukanController::class,'hasil'])->middleware('check-permission:superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpengujian|picpenindakan');
Route :: post('/rujukk',[RujukanController::class,'kirim'])->middleware('check-permission:infokom|superadmin|picinfokom');
Route :: post('/rujukkon',[RujukanController::class,'konfir'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpengujian|picpenindakan');
Route :: put('/rujukhasil/{id}',[RujukanController::class,'rujukh'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpengujian|picpenindakan');
Route :: get('/rujukhasil/{id}/edit',[RujukanController::class,'rujukha'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpengujian|picpenindakan');
Route :: post('/kirimhasil',[RujukanController::class,'kirimhasil'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpengujian|picpenindakan');
Route :: get('/formkembali/{id}',[RujukanController::class,'kembali'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpengujian|picpenindakan');
Route :: put('/kembali/{id}',[RujukanController::class,'kembalis'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpengujian|picpenindakan');
Route :: get('/inforujuk',[RujukanController::class,'info']);
Route :: delete('/rujukan/{id}/delete',[RujukanController::class,'delete'])->middleware('check-permission:superadmin');

Route :: get('/rujukan-v2',[RujukanNewController::class,'rujukan']);
Route :: get('/v2-formrujukan',[RujukanNewController::class,'formrujuk'])->middleware('check-permission:infokom|superadmin|picinfokom');
Route :: post('/v2-rujukan-store',[RujukanNewController::class,'store'])->middleware('check-permission:infokom|superadmin|picinfokom');
Route :: get('/v2-rujukan-view',[RujukanNewController::class,'view'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|kabalai|picinfokom|picpenindakan');
Route :: get('/v2-rujukan/{id}/detail',[RujukanNewController::class,'show'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|kabalai|picinfokom|picpenindakan');
Route :: delete('/v2-rujukan/{id}/delete',[RujukanNewController::class,'delete'])->middleware('check-permission:superadmin');
Route :: get('/v2-rujuk-download/storage/rujukan/{id}',[RujukanNewController::class,'download']);
Route :: get('/v2-rujukan/{id}/edit',[RujukanNewController::class,'edit'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpenindakan');
Route :: put('/v2-rujukan/{id}/update',[RujukanNewController::class,'update'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpenindakan');
Route :: get('/v2-rujukan/{id}/cetak',[RujukanNewController::class,'cetak'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|kabalai|picinfokom|picpenindakan');
Route :: post('/v2-rujukk',[RujukanNewController::class,'kirim'])->middleware('check-permission:infokom|superadmin|picinfokom');
Route :: get('/v2-formkembali/{id}',[RujukanNewController::class,'kembali'])->middleware('check-permission:kabalai|superadmin');
Route :: put('/v2-kembali/{id}',[RujukanNewController::class,'kembalis'])->middleware('check-permission:kabalai|superadmin');
Route :: put('/v2-tindak-store/{id}',[RujukanNewController::class,'tindak'])->middleware('check-permission:kabalai|superadmin');
Route :: get('/v2-rujuk-hasil/{id}/edit',[RujukanNewController::class,'rujukha'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpenindakan');
Route :: put('/v2-rujuk-hasil/{id}',[RujukanNewController::class,'rujukh'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpenindakan');
Route :: post('/v2-rujuk-kirim-hasil',[RujukanNewController::class,'kirimhasil'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpenindakan');
Route :: post('/v2-rujuk-selesai',[RujukanNewController::class,'selesai'])->middleware('check-permission:kabalai|superadmin');
Route :: get('/v2-info-rujuk',[RujukanNewController::class,'info']);

Route :: get('/rujukan-v3',[SeppuloRujukanController::class,'rujukan']);
Route :: get('/v3-formrujukan',[SeppuloRujukanController::class,'formrujuk'])->middleware('check-permission:infokom|superadmin|picinfokom');
Route :: post('/v3-rujukan-store',[SeppuloRujukanController::class,'store'])->middleware('check-permission:infokom|superadmin|picinfokom');
Route :: get('/v3-rujukan-view',[SeppuloRujukanController::class,'view'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|kabalai|picinfokom|picpenindakan|picinspeksi|picpengujian')->name('seppulov3.view');
Route :: get('/v3-rujukan/{id}/detail',[SeppuloRujukanController::class,'show'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|kabalai|picinfokom|picpenindakan|picinspeksi|picpengujian');
Route :: delete('/v3-rujukan/{id}/delete',[SeppuloRujukanController::class,'delete'])->middleware('check-permission:superadmin|picinfokom');
Route :: get('/v3-rujuk-download/storage/rujukan/{id}',[SeppuloRujukanController::class,'download']);
Route :: get('/v3-rujukan/{id}/edit',[SeppuloRujukanController::class,'edit'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpenindakan|picinspeksi|picpengujian');
Route :: put('/v3-rujukan/{id}/update',[SeppuloRujukanController::class,'update'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpenindakan|picinspeksi|picpengujian');
Route :: get('/v3-rujukan/{id}/{idhasil}/cetak',[SeppuloRujukanController::class,'cetak'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|kabalai|picinfokom|picpenindakan|picinspeksi|picpengujian');
Route :: post('/v3-rujukk',[SeppuloRujukanController::class,'kirim'])->middleware('check-permission:infokom|superadmin|picinfokom');
Route :: get('/v3-formkembali/{id}',[SeppuloRujukanController::class,'kembali'])->middleware('check-permission:kabalai|superadmin');
Route :: put('/v3-kembali/{id}',[SeppuloRujukanController::class,'kembalis'])->middleware('check-permission:kabalai|superadmin');
Route :: post('/v3-tindak-store/{id}',[SeppuloRujukanController::class,'tindak'])->middleware('check-permission:kabalai|superadmin');
Route :: get('/v3-rujuk-hasil/{id}/edit',[SeppuloRujukanController::class,'rujukha'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpenindakan|picinspeksi|picpengujian');
Route :: put('/v3-rujuk-hasil/{id}',[SeppuloRujukanController::class,'rujukh'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpenindakan|picinspeksi|picpengujian');
Route :: post('/v3-rujuk-kirim-hasil',[SeppuloRujukanController::class,'kirimhasil'])->middleware('check-permission:infokom|superadmin|penindakan|pemeriksaan|pengujian|picinfokom|picpenindakan|picinspeksi|picpengujian');
Route :: post('/v3-rujuk-selesai',[SeppuloRujukanController::class,'selesai'])->middleware('check-permission:kabalai|superadmin');
Route :: get('/v3-info-rujuk',[SeppuloRujukanController::class,'info']);
Route :: get('/v3-form-kembali-hasil/{id}',[SeppuloRujukanController::class,'kembalihasil'])->middleware('check-permission:kabalai|superadmin');
Route :: put('/v3-kembali-hasil/{id}',[SeppuloRujukanController::class,'kembalihasils'])->middleware('check-permission:kabalai|superadmin');

Route :: get('/online-sppd',[SPDController::class,'view'])->name('sppd.view');
Route :: get('/sppd-formulir',[SPDController::class,'form']);
Route :: get('/sppd-formulir-external',[SPDController::class,'formex']);
Route :: post('/sppd-store',[SPDController::class,'store']);
Route :: post('/sppd-store-ex',[SPDController::class,'storeex']);
// Route :: get('/sppd-view',[SPDController::class,'view']);
Route :: get('/sppd-detail/{id}',[SPDController::class,'detail']);
Route :: get('/sppd-detail-external/{id}',[SPDController::class,'detailex']);
Route :: get ('/show-nip/{id}',[SPDController::class,'show']);
Route :: post ('/sppd-kirim/{id}',[SPDController::class,'kirim']);
Route :: post ('/sppd-kirim-external/{id}',[SPDController::class,'kirimex']);
Route :: get ('/sppd-edit/{id}',[SPDController::class,'edit']);
Route :: get ('/sppd-edit-external/{id}',[SPDController::class,'editex']);
Route :: put ('/sppd-update/{id}',[SPDController::class,'update']);
Route :: put ('/sppd-update-external/{id}',[SPDController::class,'updateex']);
Route :: get('/sppd-view-admin',[SPDController::class,'viewadmin'])->name('sppd.viewadmin')->middleware('check-permission:admin|superadmin');
Route :: get('/sppd-approved/{id}',[SPDController::class,'approv'])->middleware('check-permission:admin|superadmin');
Route :: get('/sppd-approved-external/{id}',[SPDController::class,'approvex'])->middleware('check-permission:admin|superadmin');
Route :: delete('/sppd-delete/{id}',[SPDController::class,'destroy']);
Route :: delete('/sppd-delete-external/{id}',[SPDController::class,'destroyex']);
Route :: delete('/sppd-delete/{id}/admin',[SPDController::class,'destroyadmin'])->middleware('check-permission:admin|superadmin');
Route :: delete('/sppd-delete-external/{id}/admin',[SPDController::class,'destroyadminex'])->middleware('check-permission:admin|superadmin');
Route :: get('/sppd-cetak/{id}',[SPDController::class,'cetak'])->middleware('check-permission:admin|superadmin');
Route :: get('/sppd-cetak-external/{id}',[SPDController::class,'cetakex'])->middleware('check-permission:admin|superadmin');
Route :: get('/sppd-nomor-add/{id}',[SPDController::class,'add'])->middleware('check-permission:admin|superadmin');
Route :: get('/sppd-nomor-add-external/{id}',[SPDController::class,'addex'])->middleware('check-permission:admin|superadmin');
Route :: put ('/sppd-nomor-store/{id}',[SPDController::class,'updatenumber']);
Route :: put ('/sppd-nomor-store-external/{id}',[SPDController::class,'updatenumberex']);
Route :: get('/sppd-download/storage/st/{id}',[SPDController::class,'dwn']);
Route :: post ('/sppd-filter-admin',[SPDController::class,'filteradmin']);
Route :: post ('/sppd-filter',[SPDController::class,'filterp']);
Route :: get('/sppd-nomor-edit/{id}',[SPDController::class,'nomoredit'])->middleware('check-permission:admin|superadmin');
Route :: get('/sppd-nomor-edit-external/{id}',[SPDController::class,'nomoreditex'])->middleware('check-permission:admin|superadmin');

Route :: get('/siikma',[SikamaController::class,'index'])->name('siikma.index');
Route :: get('/formizin',[SikamaController::class,'form']);
Route :: post('/izinstore',[SikamaController::class,'store']);
Route :: get('/daftarizin',[SikamaController::class,'daftar'])->name('siikma.daftar');
Route :: put('/editizin/{id}',[SikamaController::class,'edit']);
Route :: get('/rekapizin',[SikamaController::class,'rekap'])->middleware('check-permission:superadmin|ktu|pickepegawaian|picinfokom|picinspeksi|picsertifikasi|picpengujian|picpenindakan');
Route :: get('/konfizin/{id}',[SikamaController::class,'konfir'])->middleware('check-permission:superadmin|ktu|pickepegawaian|picinfokom|picinspeksi|picsertifikasi|picpengujian|picpenindakan');
Route :: put('/konfirstore/{id}',[SikamaController::class,'konfirs'])->middleware('check-permission:superadmin|ktu|pickepegawaian|picinfokom|picinspeksi|picsertifikasi|picpengujian|picpenindakan');
Route :: get('/cetakizin/{id}',[SikamaController::class,'cetak'])->middleware('check-permission:superadmin|ktu|pickepegawaian|picinfokom|picinspeksi|picsertifikasi|picpengujian|picpenindakan');
Route :: get('/rekapfull',[SikamaController::class,'cetakf'])->middleware('check-permission:superadmin|ktu');
Route :: get('/infoizin',[SikamaController::class,'info']);
Route :: get('/detail-izin-sikama/{id}',[SikamaController::class,'detail']);
Route :: post('/akhiri-izin/{id}',[SikamaController::class,'akhir']);
Route :: get('/acc',[SikamaController::class,'acc'])->middleware('check-permission:superadmin');

Route :: get('/adaja',[AdajaController::class,'index']);
Route :: post('/adastore',[AdajaController::class,'store']);
Route :: get('/adajav',[AdajaController::class,'adajav']);
Route :: get('/adaja/{id}/detail',[AdajaController::class,'show']);
Route :: get('/cetak',[AdajaController::class,'cetak'])->middleware('check-permission:superadmin|ktu');
Route :: post('/adajacetak',[AdajaController::class,'download'])->middleware('check-permission:superadmin|ktu');
Route :: get('/log',[AdajaController::class,'log']);

Route :: get('/smile',[SmileController::class,'index']);
Route :: get('/smile-input',[SmileController::class,'form']);
Route :: post('/smile-store',[SmileController::class,'storeLembur']);
Route :: delete('/smile/delete/{id}',[SmileController::class,'deleteLembur']);
Route :: get('/data-lembur-masuk',[SmileController::class,'lemburIncome'])->middleware('check-permission:superadmin|ktu');
Route :: get('/smile-detail/{id}',[SmileController::class,'lemburDetail']);
Route :: get('/smile-approve/{id}',[SmileController::class,'lemburApprove'])->middleware('check-permission:superadmin|ktu');
Route :: get('/smile-tolak/{id}',[SmileController::class,'lemburTolak'])->middleware('check-permission:superadmin|ktu');
Route :: put('/smile/tolak/{id}',[SmileController::class,'alasanTolak'])->middleware('check-permission:superadmin|ktu');
Route :: get('/data-lembur-terima',[SmileController::class,'lemburTerima'])->middleware('check-permission:superadmin|kepegawaian|ktu|pickepegawaian');
Route :: get('/input-nomor-surat/{id}',[SmileController::class,'lemburInNomor'])->middleware('check-permission:superadmin|kepegawaian|pickepegawaian');
Route :: put('/smile-no-spml/{id}',[SmileController::class,'lemburNomorSpml'])->middleware('check-permission:superadmin|kepegawaian|pickepegawaian');
Route :: get('/input-spml/{id}',[SmileController::class,'inputSpml'])->middleware('check-permission:superadmin|kepegawaian|pickepegawaian');
Route :: get('/download-spml/{id}',[SmileController::class,'downSpml'])->middleware('check-permission:superadmin|kepegawaian|pickepegawaian');
Route :: put('/smile-spml/{id}',[SmileController::class,'inputStoreSpml'])->middleware('check-permission:superadmin|kepegawaian|pickepegawaian');
Route :: post('/spml-priview/{id}',[SmileController::class,'view_file']);
Route :: get('/data-lembur-tolak',[SmileController::class,'lemburTolakIncome'])->middleware('check-permission:superadmin|ktu');
Route :: get('/lembur-terbit-spml',[SmileController::class,'lemburSpml'])->middleware('check-permission:superadmin|kepegawaian|ktu|pickepegawaian');
Route :: get('/input-absen/{id}/{lembur_id}',[SmileController::class,'inputAbsen'])->middleware('check-permission:superadmin|kepegawaian|pickepegawaian');
Route :: post('/smile-absen-store/{id}/{lembur_id}',[SmileController::class,'inputStoreAbsen'])->middleware('check-permission:superadmin|kepegawaian|pickepegawaian');
Route :: get('/detail-absen/{id}/{lembur_id}',[SmileController::class,'detailAbsen']);
Route :: post('/absen-priview/{id}',[SmileController::class,'view_absen']);
Route :: post('/absen-edit/{id}',[SmileController::class,'edit_absen'])->middleware('check-permission:superadmin|kepegawaian|pickepegawaian');
Route :: put('/smile-absen-edit/{id}/{lembur_id}/{user_id}',[SmileController::class,'editStoreAbsen'])->middleware('check-permission:superadmin|kepegawaian|pickepegawaian');
Route :: delete('/absen/delete/{id}/{lembur_id}/{user_id}',[SmileController::class,'deleteAbsen'])->middleware('check-permission:superadmin|kepegawaian|pickepegawaian');
Route :: post('/smile-konfirmed/{id}',[SmileController::class,'smileKonfir'])->middleware('check-permission:superadmin|kepegawaian|pickepegawaian');
Route :: get('/lembur-konfirmed',[SmileController::class,'lemburKonfir'])->middleware('check-permission:superadmin|evaluasi|ktu');
Route :: get('/smile-history',[SmileController::class,'lemburHistory']);
Route :: get('/smile-verify/{id}',[SmileController::class,'lemburVerify']);
Route :: put('/smile-verified/{id}',[SmileController::class,'lemburVerified']);
Route :: get('/data-lembur-menunggu-konfirmasi',[SmileController::class,'lemburGetKonfir'])->middleware('check-permission:superadmin|ktu');
Route :: get('/smile-ttd/{id}',[SmileController::class,'lemburTtd']);
Route :: get('/smile-download',[SmileController::class,'lemburDown'])->middleware('check-permission:superadmin|ktu|evaluasi');
Route :: post('/smile-downloaded',[SmileController::class,'lemburDownProses'])->middleware('check-permission:superadmin|ktu|evaluasi');
Route :: get('/smile-download/{id}',[SmileController::class,'lemburDownDetail'])->middleware('check-permission:superadmin|ktu|evaluasi');
Route :: get('/about-smile',[SmileController::class,'aboutSmile']);
Route :: get('/lembur-selesai',[SmileController::class,'lemburSelesai'])->middleware('check-permission:superadmin|ktu|evaluasi');
Route :: get('/smile-revisi/{id}',[SmileController::class,'lemburRevisi'])->middleware('check-permission:superadmin|evaluasi');
Route :: put('/smile/revisi/{id}',[SmileController::class,'alasanRevisi'])->middleware('check-permission:superadmin|evaluasi');
Route :: get('/data-lembur-dikembalikan',[SmileController::class,'lemburKembali'])->middleware('check-permission:superadmin|evaluasi|kepegawaian|ktu|pickepegawaian');
Route :: post('/smile-konfirmed-revisi/{id}',[SmileController::class,'smileKonfirRevisi'])->middleware('check-permission:superadmin|kepegawaian|pickepegawaian');
Route :: post('/smile-konfirmed-revisi-ktu/{id}',[SmileController::class,'smileKonfirRevisiKtu'])->middleware('check-permission:superadmin|kepegawaian|pickepegawaian');
Route :: put('/smile-approved/{id}',[SmileController::class,'smileApproved'])->middleware('check-permission:superadmin|evaluasi');

Route :: get('/sipintar-v1',[SipintarController::class,'index']);
Route :: get('/sipintar/data-tamu',[SipintarController::class,'dataTamu'])->name('sipintar.view-tamu')->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');
Route :: get('/sipintar/data-tamu/{id}/detail',[SipintarController::class,'detailTamu'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');
Route :: delete('/sipintar/data-tamu/{id}/delete',[SipintarController::class,'deleteTamu'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');
Route :: post('/sipintar/data-tamu/filter',[SipintarController::class,'filterTamu'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');
Route :: get('/sipintar/data-petugas',[SipintarController::class,'dataTugas'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');
Route :: get('/sipintar/data-survey',[SipintarController::class,'dataSurvey'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');
Route :: post('/sipintar/data-survey/filter',[SipintarController::class,'filterSurvey'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');
Route :: get('/sipintar/petugas-input',[SipintarController::class,'inputTugas'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');
Route :: post('/sipintar/petugas-store',[SipintarController::class,'storeTugas'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');
Route :: get('/sipintar/data-tamu/{id}/edit',[SipintarController::class,'editTugas'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');
Route :: put('/sipintar/petugas-update/{id}',[SipintarController::class,'updateTugas'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');
Route :: delete('/sipintar/data-petugas/{id}/delete',[SipintarController::class,'deleteTugas'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');
Route :: delete('/sipintar/data-survey/{id}/delete',[SipintarController::class,'deleteSurvey'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');
Route :: put('/sipintar/update-status/{id}',[SipintarController::class,'updateSts'])->middleware('check-permission:infokom|superadmin|sertifikasi|picinfokom|picsertifikasi');

Route :: get('/bmn',[BMNController::class,'index']);
Route :: get('/bmn/bast-pengembalian',[BMNController::class,'bstkembali'])->name('bmn.view-kembali');
Route :: get('/bmn/bast-pengembalian-input',[BMNController::class,'bstkembaliinput']);
Route :: post('/bmn/bast-pengembalian-store',[BMNController::class,'bstkembalistore']);
Route :: get('/bmn/bast-pengembalian-detail/{id}',[BMNController::class,'bstkembalidetail']);
Route :: get('/bmn/bast-pengembalian-edit/{id}',[BMNController::class,'bstkembaliedit']);
Route :: put('/bmn/bast-pengembalian-update/{id}',[BMNController::class,'bstkembaliupdate']);
Route :: put('/bmn/bast-peminjaman-update/{id}',[BMNController::class,'bstpinjamupdate']);
Route :: delete('/bmn/delete-bast-pengembalian/{id}',[BMNController::class,'bstkembalidelete']);
Route :: get('/bmn/bast-peminjaman-edit/{id}',[BMNController::class,'bstpinjamedit']);
Route :: get('/bmn/bast-pengembalian-approved/{id}',[BMNController::class,'approvkembali']);
Route :: get('/bmn/bast-peminjaman-approved/{id}',[BMNController::class,'approvpinjam']);
Route :: get('/bmn/bast-pengembalian-nomor-add/{id}',[BMNController::class,'add']);
Route :: put('/bmn/bast-pengembalian-add-nomor-surat/{id}',[BMNController::class,'numberadd']);
Route :: get('/bmn/bast-pengembalian-nomor-edit/{id}',[BMNController::class,'numberedit']);
Route :: put('/bmn/bast-pengembalian-nomor-update/{id}',[BMNController::class,'numberupdate']);
Route :: get('/bmn/bast-pengembalian-cetak/{id}',[BMNController::class,'cetak']);
Route :: get('/bmn/bast-peminjaman-cetak/{id}',[BMNController::class,'cetakpinjam']);
Route :: get('/bmn/bast-peminjaman',[BMNController::class,'bstpinjam'])->name('bmn.view-pinjam');
Route :: get('/bmn/bast-peminjaman-input',[BMNController::class,'bstpinjaminput']);
Route :: post('/bmn/bast-peminjaman-store',[BMNController::class,'bstpinjamstore']);
Route :: get ('/show-barang/{id}',[BMNController::class,'show']);
Route :: get ('/show-ruang/{id}',[BMNController::class,'showruang']);
Route :: get('/bmn/pinjam-kendaraan',[BMNController::class,'pinjamKendaraan'])->name('bmn.view-pinjam-kendaraan');
Route :: post('/bmn/peminjaman-mobil-filter',[BMNController::class,'pinjamKendFil']);
Route :: get ('/bmn/peminjaman-mobil/{id}',[BMNController::class,'pinjamMobil']);
Route :: post('/bmn/peminjaman-kendaraan-store/{id}',[BMNController::class,'pinjamMobilStore']);
Route :: get('/bmn/admin/peminjaman-kendaraan',[BMNController::class,'adminPinKen'])->name('bmn.view-admin-pinjam-kendaraan')->middleware('check-permission:superadmin|perlengkapan');
Route :: post('/bmn/peminjaman-kendaraan-approve/{id}',[BMNController::class,'pinjamMobilaprov'])->middleware('check-permission:superadmin|perlengkapan');
Route :: put('/bmn/peminjaman-kendaraan-reject/{id}',[BMNController::class,'pinjamMobilReject'])->middleware('check-permission:superadmin|perlengkapan');
Route :: post('/bmn/admin/peminjaman-kendaraan/filter',[BMNController::class,'pinjamMobilFil'])->middleware('check-permission:superadmin|perlengkapan');
Route :: delete('/bmn/peminjaman-kendaraan-delete/{id}',[BMNController::class,'pinjamMobilDel'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/daftar-driver',[BMNController::class,'daftarDriv'])->name('bmn.view-admin-daftar-driver')->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/input-data-driver',[BMNController::class,'inputDriv'])->middleware('check-permission:superadmin|perlengkapan');
Route :: post('/bmn/admin/input-driver-store',[BMNController::class,'inputDrivStore'])->middleware('check-permission:superadmin|perlengkapan');
Route :: put('/bmn/admin/update-status-driver/{id}',[BMNController::class,'drivUpdtSts'])->middleware('check-permission:superadmin|perlengkapan');
Route :: delete('/bmn/admin/delete-driver/{id}',[BMNController::class,'drivDel'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/daftar-kendaraan',[BMNController::class,'daftarKend'])->name('bmn.view-admin-daftar-kendaraan')->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/input-data-kendaraan',[BMNController::class,'inputCar'])->middleware('check-permission:superadmin|perlengkapan');
Route :: post('/bmn/admin/input-kendaraan-store',[BMNController::class,'inputCarStore'])->middleware('check-permission:superadmin|perlengkapan');
Route :: put('/bmn/admin/update-status-kendaraan/{id}',[BMNController::class,'carUpdtSts'])->middleware('check-permission:superadmin|perlengkapan');
Route :: delete('/bmn/admin/delete-kendaraan/{id}',[BMNController::class,'carDel'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/edit-data-driver/{id}',[BMNController::class,'drivEdit'])->middleware('check-permission:superadmin|perlengkapan');
Route :: put('/bmn/admin/update-driver-store/{id}',[BMNController::class,'drivUpdate'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/edit-data-kendaraan/{id}',[BMNController::class,'carEdit'])->middleware('check-permission:superadmin|perlengkapan');
Route :: put('/bmn/admin/update-kendaraan-store/{id}',[BMNController::class,'carUpdate'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/daftar-ruangan',[BMNController::class,'daftarRuang'])->name('bmn.view-admin-daftar-ruang')->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/input-data-ruangan',[BMNController::class,'inputRuang'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/edit-data-ruangan/{id}',[BMNController::class,'ruangEdit'])->middleware('check-permission:superadmin|perlengkapan');
Route :: post('/bmn/admin/input-ruangan-store',[BMNController::class,'inputRuangStore'])->middleware('check-permission:superadmin|perlengkapan');
Route :: put('/bmn/admin/update-ruangan-store/{id}',[BMNController::class,'ruangUpdate'])->middleware('check-permission:superadmin|perlengkapan');
Route :: delete('/bmn/admin/delete-ruang/{id}',[BMNController::class,'ruangDel'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/daftar-barang',[BMNController::class,'daftarBarang'])->name('bmn.view-admin-daftar-barang')->middleware('check-permission:superadmin|perlengkapan');
Route::match(['get', 'post'], '/bmn/admin/daftar-barang/filter', [BMNController::class, 'barangFil'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/detail-barang/{id}',[BMNController::class,'detailBarang'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/input-data-barang',[BMNController::class,'inputBarang'])->middleware('check-permission:superadmin|perlengkapan');
Route :: post('/bmn/admin/input-barang-store',[BMNController::class,'inputBarangStore'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/edit-data-barang/{id}',[BMNController::class,'barangEdit'])->middleware('check-permission:superadmin|perlengkapan');
Route :: put('/bmn/admin/update-barang-store/{id}',[BMNController::class,'barangUpdate'])->middleware('check-permission:superadmin|perlengkapan');
Route :: delete('/bmn/admin/delete-barang/{id}',[BMNController::class,'barangDel'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/pinjam-aula',[BMNController::class,'pinjamAula'])->name('bmn.view-pinjam-aula');
Route :: get ('/bmn/peminjaman-aula/{id}',[BMNController::class,'peminjamAula']);
Route :: post('/bmn/peminjaman-aula-store/{id}',[BMNController::class,'pinjamAulaStore']);
Route :: post('/bmn/peminjaman-aula-filter',[BMNController::class,'pinjamAuladFil']);
Route :: get('/bmn/admin/daftar-aula',[BMNController::class,'daftarAula'])->name('bmn.view-admin-daftar-aula')->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/input-data-aula',[BMNController::class,'inputAula'])->middleware('check-permission:superadmin|perlengkapan');
Route :: post('/bmn/admin/input-aula-store',[BMNController::class,'inputAulaStore'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/edit-data-aula/{id}',[BMNController::class,'aulaEdit'])->middleware('check-permission:superadmin|perlengkapan');
Route :: put('/bmn/admin/update-aula-store/{id}',[BMNController::class,'aulaUpdate'])->middleware('check-permission:superadmin|perlengkapan');
Route :: put('/bmn/admin/update-status-aula/{id}',[BMNController::class,'aulaUpdtSts'])->middleware('check-permission:superadmin|perlengkapan');
Route :: delete('/bmn/admin/delete-aula/{id}',[BMNController::class,'aulaDel'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/peminjaman-aula',[BMNController::class,'adminPinAula'])->name('bmn.view-admin-pinjam-aula')->middleware('check-permission:superadmin|perlengkapan');
Route :: post('/bmn/peminjaman-aula-approve/{id}',[BMNController::class,'pinjamAulaApprov'])->middleware('check-permission:superadmin|perlengkapan');
Route :: delete('/bmn/peminjaman-aula-delete/{id}',[BMNController::class,'pinjamAulaDel'])->middleware('check-permission:superadmin|perlengkapan');
Route :: post('/bmn/admin/peminjaman-aula/filter',[BMNController::class,'pinjamAulaFil'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/pinjam-non-bast',[BMNController::class,'nonBast'])->name('bmn.non-bast');
Route :: get('/bmn/input-pinjam-non-bast',[BMNController::class,'nonBastInput']);
Route :: post('/bmn/pinjam-non-bast/store',[BMNController::class,'nonBastStore']);
Route :: get('/bmn/pinjam-nonbast-detail/{id}',[BMNController::class,'nonBastDetail']);
Route :: put('/bmn/pinjam-non-bast-approved/{id}',[BMNController::class,'nonBastAppr'])->middleware('check-permission:superadmin|perlengkapan');
Route :: get('/bmn/admin/pinjam-non-bast',[BMNController::class,'nonBastAdmin'])->name('bmn.non-bast-admin');
Route :: post('/bmn/admin/pinjam-non-bast/filter',[BMNController::class,'nonBastFil'])->middleware('check-permission:superadmin|perlengkapan');
Route :: delete('/bmn/delete-pinjam-non-bast/{id}',[BMNController::class,'nonBastDel']);
Route :: delete('/bmn/admin/delete-pinjam-non-bast/{id}',[BMNController::class,'adminNonBastDel']);
Route :: get('/bmn/dbr/{id}',[BMNController::class,'dbrView'])->name('bmn.dbr-view');
Route :: post('/bmn/konfirmasi-dbr/{id}',[BMNController::class,'dbrKonf']);
Route :: get('/bmn/dbr/download-qr/{id}',[BMNController::class,'dbrDownload'])->middleware('check-permission:superadmin|perlengkapan');

Route :: get('/berakhlak',[BerakhlakController::class,'index']);
Route :: get('/{id}/image',[BerakhlakController::class,'image']);
Route :: get('/{id}/image-input',[BerakhlakController::class,'imageInput']);
Route :: post('/image-store/{id}',[BerakhlakController::class,'imageStore']);
Route :: delete('/berakhlak-image/delete/{id}',[BerakhlakController::class,'deleteImage']);
Route :: get('/{url}/image-detail/{id}',[BerakhlakController::class,'imageDetail']);
Route :: get('/{url}/edit-image/{id}',[BerakhlakController::class,'imageEdit']);
Route :: get('/{id}/video',[BerakhlakController::class,'video']);
Route :: get('/{id}/video-input',[BerakhlakController::class,'videoInput']);
Route :: post('/video-store/{id}',[BerakhlakController::class,'videoStore']);
Route :: delete('/berakhlak-video/delete/{id}',[BerakhlakController::class,'deleteVideo']);
Route :: get('/{url}/video-detail/{id}',[BerakhlakController::class,'videoDetail']);
Route :: get('/{id}/file',[BerakhlakController::class,'file']);
Route :: get('/{id}/file-input',[BerakhlakController::class,'fileInput']);
Route :: post('/file-store/{id}',[BerakhlakController::class,'fileStore']);
Route :: delete('/berakhlak-file/delete/{id}',[BerakhlakController::class,'deleteFile']);
Route :: get('/{url}/file-detail/{id}',[BerakhlakController::class,'fileDetail']);
Route :: get('/{id}/link',[BerakhlakController::class,'link']);
Route :: get('/{id}/link-input',[BerakhlakController::class,'linkInput']);
Route :: post('/link-store/{id}',[BerakhlakController::class,'linkStore']);
Route :: delete('/berakhlak-link/delete/{id}',[BerakhlakController::class,'deleteLink']);
Route :: get('/{url}/link-detail/{id}',[BerakhlakController::class,'linkDetail']);

Route :: get('/logview',[LogController::class,'index']);
Route :: get('/logdelete',[LogController::class,'destroy']);
Route :: get('/logdetail/{id}',[LogController::class,'show']);

Route :: get('/serambi',[SerambiController::class,'index']);
Route :: get('/tambah-file-serambi',[SerambiController::class,'form']);
Route :: post('/serambi_store',[SerambiController::class,'store']);
Route :: get('/serambi/{id}/edit',[SerambiController::class,'edit']);
Route :: put('/serambi_update/{id}',[SerambiController::class,'update']);
Route :: delete('/serambi/{id}/delete',[SerambiController::class,'delete']);
Route :: get('/serambi/{id}/kirim',[SerambiController::class,'send']);

Route :: get('/send',[FrontController::class,'send']);
});

Route :: get('/pelayanan',[BerakhlakController::class,'pelayanan']);
Route :: get('/view-foto/pelayanan',[BerakhlakController::class,'fotoPelayanan']);
Route :: get('/view-video/pelayanan',[BerakhlakController::class,'videoPelayanan']);
Route :: get('/akuntabel',[BerakhlakController::class,'akuntabel']);
Route :: get('/view-foto/akuntabel',[BerakhlakController::class,'fotoAkuntabel']);
Route :: get('/view-video/akuntabel',[BerakhlakController::class,'videoAkuntabel']);
Route :: get('/kompeten',[BerakhlakController::class,'kompeten']);
Route :: get('/view-foto/kompeten',[BerakhlakController::class,'fotoKompeten']);
Route :: get('/view-video/kompeten',[BerakhlakController::class,'videoKompeten']);
Route :: get('/harmonis',[BerakhlakController::class,'harmonis']);
Route :: get('/view-foto/harmonis',[BerakhlakController::class,'fotoHarmonis']);
Route :: get('/view-video/harmonis',[BerakhlakController::class,'videoHarmonis']);
Route :: get('/loyal',[BerakhlakController::class,'loyal']);
Route :: get('/view-foto/loyal',[BerakhlakController::class,'fotoLoyal']);
Route :: get('/view-video/loyal',[BerakhlakController::class,'videoLoyal']);
Route :: get('/adaptif',[BerakhlakController::class,'adaptif']);
Route :: get('/view-foto/adaptif',[BerakhlakController::class,'fotoAdaptif']);
Route :: get('/view-video/adaptif',[BerakhlakController::class,'videoAdaptif']);
Route :: get('/kolaboratif',[BerakhlakController::class,'kolaboratif']);
Route :: get('/view-foto/kolaboratif',[BerakhlakController::class,'fotoKolaboratif']);
Route :: get('/view-video/kolaboratif',[BerakhlakController::class,'videoKolaboratif']);

Route :: get ('/show/{id}',[ExtensionController::class,'latarshow']);

Route :: get ('/aplikasi',[FrontController::class,'aplikasi']);

Route::get('/', [App\Http\Controllers\FrontController::class, 'index'])->name('homepage');
Route::get('post/{slug}', [App\Http\Controllers\FrontController::class, 'show'])->name('show');
Route::post('/comment', [App\Http\Controllers\FrontController::class, 'store']);
Route::get('/all_news', [App\Http\Controllers\FrontController::class, 'allnew']);
Route::get('/populer', [App\Http\Controllers\FrontController::class, 'populer']);
Route::get('/vc/{id}', [App\Http\Controllers\FrontController::class, 'vc']);
Route::get('/vt/{id}', [App\Http\Controllers\FrontController::class, 'vt']);
Route::get('/search', [App\Http\Controllers\FrontController::class, 'search']);
Route::get('category/{category:slug}', [App\Http\Controllers\FrontController::class, 'category'])->name('category');
Route::get('tag/{tag:slug}', [App\Http\Controllers\FrontController::class, 'tag'])->name('tag');